/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScansIdRouteImport } from './routes/scans.$id'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api.webhooks.github'
import { Route as ApiScanInstantRouteImport } from './routes/api.scan.instant'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansIdRoute = ScansIdRouteImport.update({
  id: '/scans/$id',
  path: '/scans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanInstantRoute = ApiScanInstantRouteImport.update({
  id: '/api/scan/instant',
  path: '/api/scan/instant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/scans/$id': typeof ScansIdRoute
  '/api/scan/instant': typeof ApiScanInstantRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/scans/$id': typeof ScansIdRoute
  '/api/scan/instant': typeof ApiScanInstantRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/scans/$id': typeof ScansIdRoute
  '/api/scan/instant': typeof ApiScanInstantRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/policies'
    | '/sitemap.xml'
    | '/scans/$id'
    | '/api/scan/instant'
    | '/api/webhooks/github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/policies'
    | '/sitemap.xml'
    | '/scans/$id'
    | '/api/scan/instant'
    | '/api/webhooks/github'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/policies'
    | '/sitemap.xml'
    | '/scans/$id'
    | '/api/scan/instant'
    | '/api/webhooks/github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PoliciesRoute: typeof PoliciesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ScansIdRoute: typeof ScansIdRoute
  ApiScanInstantRoute: typeof ApiScanInstantRoute
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans/$id': {
      id: '/scans/$id'
      path: '/scans/$id'
      fullPath: '/scans/$id'
      preLoaderRoute: typeof ScansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan/instant': {
      id: '/api/scan/instant'
      path: '/api/scan/instant'
      fullPath: '/api/scan/instant'
      preLoaderRoute: typeof ApiScanInstantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PoliciesRoute: PoliciesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ScansIdRoute: ScansIdRoute,
  ApiScanInstantRoute: ApiScanInstantRoute,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
