// Supabase auth middleware for server functions.
//
// Originally generated by Lovable, then extended (batch 3) so the Supabase
// client used for JWT verification is created ONCE and shared across requests
// instead of being re-instantiated per call. Handlers use the service-role
// client (client.server.ts) for data access; this middleware's only job is to
// authenticate the caller and expose their user id.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

// The fetch wrapper is a pure function of the API key, so cache it instead of
// allocating a new closure per request.
const supabaseFetchCache = new Map<string, typeof fetch>();

function getSupabaseFetch(supabaseKey: string): typeof fetch {
  let wrapped = supabaseFetchCache.get(supabaseKey);
  if (!wrapped) {
    wrapped = (input, init) => {
      const headers = new Headers(
        typeof Request !== "undefined" && input instanceof Request
          ? input.headers
          : undefined,
      );

      if (init?.headers) {
        new Headers(init.headers).forEach((value, key) =>
          headers.set(key, value),
        );
      }

      // New Supabase API keys are opaque strings, not bearer JWTs.
      if (
        isNewSupabaseApiKey(supabaseKey) &&
        headers.get("Authorization") === `Bearer ${supabaseKey}`
      ) {
        headers.delete("Authorization");
      }

      headers.set("apikey", supabaseKey);
      return fetch(input, { ...init, headers });
    };
    supabaseFetchCache.set(supabaseKey, wrapped);
  }
  return wrapped;
}

// Shared, lazily-created client used ONLY for auth.getClaims(token). Because
// the token is passed as an argument, no per-request Authorization header or
// client instantiation is required.
let verifyClient: ReturnType<typeof createClient<Database>> | null = null;

function getVerifyClient(): ReturnType<typeof createClient<Database>> {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (!verifyClient) {
    verifyClient = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          fetch: getSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      },
    );
  }
  return verifyClient;
}

/**
 * Verifies a Supabase access token and returns the authenticated user.
 * Shared by requireSupabaseAuth and by route handlers that authenticate
 * request headers directly (e.g. api.scan.instant.ts), so no request ever
 * allocates its own Supabase client.
 */
export async function verifySupabaseToken(token: string) {
  const { data, error } = await getVerifyClient().auth.getClaims(token);
  if (error || !data?.claims) {
    throw new Error("Unauthorized: Invalid token");
  }
  if (!data.claims.sub) {
    throw new Error("Unauthorized: No user ID found in token");
  }
  return { userId: data.claims.sub, claims: data.claims };
}

export const requireSupabaseAuth = createMiddleware({
  type: "function",
}).server(async ({ next }) => {
  const request = getRequest();

  if (!request?.headers) {
    throw new Error("Unauthorized: No request headers available");
  }

  const authHeader = request.headers.get("authorization");

  if (!authHeader) {
    throw new Error("Unauthorized: No authorization header provided");
  }

  if (!authHeader.startsWith("Bearer ")) {
    throw new Error("Unauthorized: Only Bearer tokens are supported");
  }

  const token = authHeader.replace("Bearer ", "");
  if (!token) {
    throw new Error("Unauthorized: No token provided");
  }

  if (token.split(".").length !== 3) {
    throw new Error("Unauthorized: Invalid token");
  }

  const { userId, claims } = await verifySupabaseToken(token);

  return next({
    context: {
      supabase: getVerifyClient(),
      userId,
      claims,
    },
  });
});
